<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>MvcReportViewer.Example</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="App_Data\Reports\DatabaseDataSet.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>DatabaseDataSet.xsd</DependentUpon>
    </Compile>
    <Compile Update="Global.asax.cs">
      <DependentUpon>Global.asax</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Content Include="App_Data\Database.mdf" />
    <Content Include="App_Data\Database_log.ldf">
      <DependentUpon>Database.mdf</DependentUpon>
    </Content>
    <Content Include="Content\styles.css" />
    <Content Include="Global.asax" />
    <Content Include="MvcReportViewer.aspx" />
    <Content Include="MvcReportViewerErrorPage.html" />
    <Content Include="Scripts\MvcReportViewer.js" />
    <Content Include="Scripts\url.js" />
    <Content Include="SqlServerTypes\readme.htm" />
    <Content Include="SqlServerTypes\x64\msvcr120.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerTypes\x64\SqlServerSpatial140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerTypes\x86\msvcr120.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SqlServerTypes\x86\SqlServerSpatial140.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Web.config">
      <SubType>Designer</SubType>
    </Content>
    <Content Update="Web.Debug.config">
      <DependentUpon>Web.config</DependentUpon>
    </Content>
    <Content Update="Web.Release.config">
      <DependentUpon>Web.config</DependentUpon>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="App_Data\Reports\Products.rdlc" />
    <EmbeddedResource Include="App_Data\Reports\Cities.rdlc" />
    <EmbeddedResource Include="App_Data\Reports\NoDataReport.rdlc" />
    <EmbeddedResource Include="App_Data\Reports\Countries.rdlc" />
    <EmbeddedResource Include="App_Data\Reports\CitiesByCountry.rdlc" />
    <EmbeddedResource Include="App_Data\Reports\ListCountries.rdlc" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="App_Data\Reports\DatabaseDataSet.xsc">
      <DependentUpon>DatabaseDataSet.xsd</DependentUpon>
    </Content>
    <None Update="App_Data\Reports\DatabaseDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DatabaseDataSet.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </None>
    <Content Include="App_Data\Reports\DatabaseDataSet.xss">
      <DependentUpon>DatabaseDataSet.xsd</DependentUpon>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MvcReportViewer\MvcReportViewer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.WebApi" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.Bcl.Build" Version="1.0.21" />
    <PackageReference Include="Microsoft.Net.Http" Version="2.2.29" />
    <PackageReference Include="Microsoft.ReportingServices.ReportViewerControl.WebForms" Version="150.1652.0" />
    <PackageReference Include="Microsoft.SqlServer.Types" Version="170.1000.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Ninject" Version="3.3.6" />
    <PackageReference Include="Ninject.MVC5" Version="3.3.0" />
    <PackageReference Include="Ninject.Web.Common" Version="3.3.2" />
    <PackageReference Include="Ninject.Web.Common.WebHost" Version="3.3.2" />
    <PackageReference Include="WebActivatorEx" Version="2.2.0" />
  </ItemGroup>
  <PropertyGroup>
    <PostBuildEvent>if exist "$(TargetDir)MvcReportViewer.aspx" move /Y "$(TargetDir)MvcReportViewer.aspx" "$(ProjectDir)MvcReportViewer.aspx"</PostBuildEvent>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputPath>bin\</OutputPath>
  </PropertyGroup>
</Project>